name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
      actions: write
      checks: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Push gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: github-actions
          user_email: github-actions@github.com
