name: Run protoc html doc Generater
on:
  workflow_dispatch:
  push:
    paths:
      - "deepthought.proto"

jobs:
  protoc-doc:
    permissions:
      actions: write
      checks: write
      contents: write
    name: Run protoc html doc Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Generate Docs
        run: |
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
          which protoc-gen-doc
          mkdir -p ./docs
          protoc --doc_out=html,index.html:./docs deepthought.proto
      - name: Add Doc Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: ./docs/index.html
          message: "doc: Update Protobuf Documentation"
